version: '3'

services:
  user-microservice:
    container_name: user-microservice
    build: .
    command: yarn dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    network_mode: host
